server:
  port: 10001
logging.level.root: INFO
logging.level.com.example.learn.dao: DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false&serverTimezone=UTC&generateSimpleParameterMetadata=true
    username: root
    password: root
